#!/usr/bin/env php
<?php
require_once __DIR__ . '/bootstrap/autoload.php';
$container = require __DIR__ . '/bootstrap/app.php';

use Symfony\Component\Console\Application;

$application = new Application();

/*
|--------------------------------------------------------------------------
| Register Commands
|--------------------------------------------------------------------------
|
| Add classes here...
|
*/
$application->add(new \Jenerator\Command\ShowExampleJsonFromSchemaCommand($container));


$application->run();